### ISSUE TITLE
Quantity of entires 

### ISSUE THREAD

**Issue by 781330** [j26design/Ecwid-Sitemap-Generator#1]
Hi! I have more than 3500 products in store, but application scans only 100 entries - is it ok?

**Comment by jp26jp** [comment]
Interesting, that shouldn't be happening. I'll contact Ecwid's devs to see if something is preventing it from loading more than 100 products and get back to you.

**Comment by jp26jp** [comment]
The app was just updated and will now generate as many products as you need!
