### ISSUE TITLE
Pages other then products and categories

### ISSUE THREAD

**Issue by kurumbus** [j26design/Ecwid-Sitemap-Generator#3]
I think It would be great if one could include pages other than products and categories in a sitemap. I mean information about delivery, contacts etc.

**Comment by jp26jp** [comment]
Do you have a URL for an Ecwid page with that info?

**Comment by PaulusKnollus** [comment]
Hi John,

 

This is the extent of which can be altered on the Ecwid Starter site:
https://support.ecwid.com/hc/en-us/articles/207100069-Starter-site#advanceddesignsettings 

https://support.ecwid.com/hc/en-us/articles/207807915-How-to-change-Ecwid-design#changelement

 

There is no access to placing things like meta tags into the head of the Starter site’s page.  This was discovered in email correspondence with Scully on the Ecwid developer team.

 

Paul

 

Paul Knoll

Baby Mattress Covers, LLC

**Comment by kurumbus** [comment]
Sorry for bringing this up. I meant combining it with a regular crawler. I guess it's not important.

**Comment by PaulusKnollus** [comment]
The Ecwid Starter Site for which I use the Ecwid Sitemap Generator has at its main purpose to be a Store for my products.  So I want the bots to review my Product pages regularly to keep the search engines updated on any changes in them.
Delivery methods will no change much, but Google still searches out that as well -- as far as i am told by the Ecwid SEO blog post -- on a regular basis.
As far as you customer contacts, I would think you would want to keep those secure and private.  If you meant your contact info, Google also searches that regularly as well.
I think what jp26jp was trying to imply is that a normal Ecwid page does not include much of that stuff....
