### ISSUE TITLE
Wrong address shema

### ISSUE THREAD

**Issue by tsunagari** [j26design/Ecwid-Sitemap-Generator#4]
Hi.
Thank you for this automatic Sitemap.
However, address in the site map are using this patern (MyStoreURL/ecwidproduct-preference or -creference for category)
But, this give an eror since Ecwid use this patern : MyStoreURL#!/ecwidproduct/p/reference (or /c/reference for category)

Could you update your script to reflect actual Ecwid address patern ?
Thank you very much.

**Comment by PaulusKnollus** [comment]
I am quite sure the Ecwid web engineers are working on this.
The URL that displays in my browser looks like this type:  (MyStoreURL/ecwidproduct-preference or -creference for category)
But the URL that shows to Google Shopping and the Product SEO looks like the latter with the hashtag.
It is not merely a Sitemap Generator issue but more extensive.  They seem to be working on it quite quickly.

**Comment by PaulusKnollus** [comment]
An Update:
Google Shopping has accommodated to the difference in URLs and my ads are for the most part all approved.  The URL without the hashtag is what shows to the customers.
The advantage to the URL without the hashtag and without the forward slashes is that it is easier to place in an .HTACCESS file without extensive coding adjustments to make it work.
The URL without the hashtag appears to me to be canonical so there is not multiple redirects from that URL.
The URL with the hashtag seems to work just fine though.

**Comment by jp26jp** [comment]
All you have to do is turn off the clean URL feature in the sitemap generator.
