### ISSUE TITLE
App does not load in ECWID store

### ISSUE THREAD

**Issue by TheRealDarthVader** [j26design/Ecwid-Sitemap-Generator#5]
Hi friends - just to let you know that I joined ECWID recently and have completed and published our store but the SiteMap app does not load in the admin of the store. I have no idea what the issue is but have tried to open the app for the last few days and the same error message persists. Please see the screenshot attached of the error message in my store admin for the app failing to load. My ECWID store ID is 11223123. Please advise. Thank you kindly
![screen shot 2017-08-17 at 08 41 11](https://user-images.githubusercontent.com/31091700/29399709-95b16904-832a-11e7-9937-d45e5cbeb9a8.png)

**Comment by jp26jp** [comment]
That's strange. When did you install the app?

**Comment by TheRealDarthVader** [comment]
Hi John,

Thank you for your kind and prompt reply.

Honestly I don’t remember when exactly I installed the app but it would have been over the last month or two while building the ECWID store.

So I just uninstalled the app now and tried to reinstall it to see if that would maybe fix something but now I get the error message that the app is having trouble installing. Please see the screenshot attached.


I did try refresh the page a number of times as the message above advises but I just get the ECWID spinning wheel while loading for a few minutes and then the same message above each time.

I am not a tech savvy person so I’m afraid I cannot explain anything more than how I have described the issue above.

Hope it helps you work out what might be wrong.

Thank you kindly,
Arryn

**Comment by jp26jp** [comment]
@Ecwid

**Comment by jp26jp** [comment]
Have you tried clearing your cache?

**Comment by TheRealDarthVader** [comment]
Ok I cleared the cache - logged out of ECWID - logged back in ECWID - tried to reinstall the app a few times - same error message unfortunately

![screen shot 2017-08-17 at 10 51 20](https://user-images.githubusercontent.com/31091700/29404238-cdd3b48a-833a-11e7-8e33-35e270d27e2d.png)

**Comment by TheRealDarthVader** [comment]
Update... I tried installing the app directly from the URL https://www.j-26.com/app-docs/ecwid/sitemap-generator/  instead of from the ECWID admin page's collection of apps. This progressed to the point of allowing the app to appear in my ECWID admin page menu but still the app comes up with an error message while trying to follow through installing... 
![screen shot 2017-08-17 at 11 05 38](https://user-images.githubusercontent.com/31091700/29404722-1562bd36-833c-11e7-89da-ac5defa3db5a.png)

**Comment by jp26jp** [comment]
Okay, I'll contact Ecwid to see what error is being reported on their end. I can't seem to reproduce it on my end so hopefully they'll have some insight.

**Comment by TheRealDarthVader** [comment]
Thank you

**Comment by jp26jp** [comment]
Ecwid wasn't able to reproduce the problem either. What browser are you using?

**Comment by TheRealDarthVader** [comment]
I have an iMac with Safari browser
![screen shot 2017-08-17 at 22 05 40](https://user-images.githubusercontent.com/31091700/29431514-78b6e82e-8398-11e7-819b-836616b58219.png)
![screen shot 2017-08-17 at 22 06 00](https://user-images.githubusercontent.com/31091700/29431520-8132e7f0-8398-11e7-8ddb-d3b85b671af9.png)

**Comment by TheRealDarthVader** [comment]
Good day. Here is a VLC screen video to show you. This is what happens with each attempt. The movie doesn’t load to the message board so I’m sending it separately in email. You can share with ECWID. Thank you kindly.

**Comment by jp26jp** [comment]
I get what is happening. Is it happening in different browsers or incognito?

**Comment by TheRealDarthVader** [comment]
Hello - no privacy or incognito settings - the app loaded through using chrome - seems the app and my safari browser are not good friends - thank you for your time and support and I hope this info has been of value to you - best regards

**Comment by jp26jp** [comment]
That's so weird. I tried using Safari with multiple stores and they didn't
have an issue. Hopefully it stops having an issue in Safari for you but
until then, I'm glad chrome is working.
