### ISSUE TITLE
huayyin

### ISSUE THREAD

**Issue by huayyin** [j26design/Ecwid-Sitemap-Generator#6]
hi, i m using Ecwid store to build my website. However i m applying the same account to build for 2 website with different type of product. However i m encounter a problem which is even i try to upload phone casing at alliphonecase.com, however the sitemap result still appear as topgymwear.com. 
so, how can i solve this type of problem?

**Comment by PaulusKnollus** [comment]
My suggestion to get the sitemap to be separate for each different business type, is to have two separate Ecwid Starter Site store accounts.  That is, place the phone case and gym wear businesses in separate Ecwid accounts, and on separate websites.
The Business level Ecwid account is said to now allow separate Ecwid accounts to be accessed by the same login interface by using the new staff function.
So, my suggestion is to have two separate Ecwid accounts, one for each product line, if you want to keep the items in the sitemaps separate...

**Comment by jp26jp** [comment]
To my knowledge, Ecwid doesn't make it possible for developers to identify which products come from which category so something like this wouldn't be possible without having more than one account.
