### ISSUE TITLE
Title Tags

### ISSUE THREAD

**Issue by PellamosDeals** [j26design/Ecwid-Sitemap-Generator#8]
Why my Title Tags appear like Contacts us? isn't supposed to appear like my SEO settings?

![untitled](https://user-images.githubusercontent.com/40199605/41282020-9e7931b4-6e3b-11e8-8a8f-82ec546f1ab5.jpg)

**Comment by jp26jp** [comment]
Yes, it should. That's very strange. You'll want to contact Ecwid about that though because the sitemap doesn't have anything to do with the title's of the pages.
