### ISSUE TITLE
the sitemap doesn't work on ecwid.com

### ISSUE THREAD

**Issue by Arano1** [j26design/Ecwid-Sitemap-Generator#9]
after making a sitemap for https://spiritualpsychicreadings.ecwid.com it is not valid on bing or on google webmaster tools.

**Comment by jp26jp** [comment]
I'm guessing you didn't upload it to a server?

[Follow this guide](https://www.j-26.com/app-docs/ecwid/sitemap-generator/where-to-host-your-ecwid-sitemap-if-you-cannot-access-your-server/)
